"""Write figures and LaTeX tables where the report (and Overleaf) expects them.

File names are stable and deterministic, so re-running an experiment overwrites
the previous file and produces a clean, reviewable Git diff::

    save_figure(fig, "model_comparison")        -> figures/generated/model_comparison.pdf
    save_latex_table(df, "model_results")       -> report/tables/generated/model_results.tex

The report includes them with ``\\generatedfigure{model_comparison}`` and
``\\generatedtable{model_results}`` (see report/main.tex).
"""
import re
from pathlib import Path
from typing import Optional

from project.utils.paths import FIGURES_GENERATED_DIR, TABLES_GENERATED_DIR

_NAME = re.compile(r"^[A-Za-z0-9][A-Za-z0-9_-]*$")

_TABLE_HEADER = (
    "% AUTO-GENERATED by project.utils.report_assets.save_latex_table -- do not edit by hand.\n"
    "% Requires \\usepackage{booktabs}.\n"
)


def _check_name(name: str) -> str:
    if not _NAME.match(name):
        raise ValueError(
            f"Invalid asset name {name!r}: use a bare stable name such as 'model_comparison' "
            "(letters, digits, '_' or '-'; no directory and no extension)."
        )
    return name


def save_figure(fig, name: str, out_dir: Optional[Path] = None, **savefig_kwargs) -> Path:
    """Save a matplotlib figure as ``<out_dir>/<name>.pdf`` (default ``figures/generated``).

    The PDF creation date is dropped so identical plots give byte-identical files.
    """
    out_dir = Path(out_dir) if out_dir is not None else FIGURES_GENERATED_DIR
    out_dir.mkdir(parents=True, exist_ok=True)
    path = out_dir / f"{_check_name(name)}.pdf"
    savefig_kwargs.setdefault("bbox_inches", "tight")
    metadata = {"CreationDate": None, **savefig_kwargs.pop("metadata", {})}
    fig.savefig(path, format="pdf", metadata=metadata, **savefig_kwargs)
    return path


def save_latex_table(df, name: str, out_dir: Optional[Path] = None, **to_latex_kwargs) -> Path:
    """Save a DataFrame as a booktabs ``tabular`` in ``<out_dir>/<name>.tex``
    (default ``report/tables/generated``).

    Caption and label are deliberately NOT part of the generated file; put them in
    the surrounding ``table`` environment inside ``report/sections/*.tex``.
    """
    out_dir = Path(out_dir) if out_dir is not None else TABLES_GENERATED_DIR
    out_dir.mkdir(parents=True, exist_ok=True)
    path = out_dir / f"{_check_name(name)}.tex"
    to_latex_kwargs.setdefault("index", False)
    to_latex_kwargs.setdefault("float_format", "%.4f")
    to_latex_kwargs.setdefault("escape", True)  # model/metric names contain '_' and '%'; pass escape=False for math
    path.write_text(_TABLE_HEADER + df.to_latex(**to_latex_kwargs), encoding="utf-8")
    return path
